Make sure log directories exist.

diff --git a/package-scripts/puppet-library/postinst b/package-scripts/puppet-library/postinst
--- a/package-scripts/puppet-library/postinst
+++ b/package-scripts/puppet-library/postinst
@@ -33,9 +33,15 @@ fi
 # Create module directory
 echo "Creating var directories"
 mkdir -m 755 -p $MOD_DIR || error_exit "Cannot create $MOD_DIR"
-
 # Set correct ownership of puppet directories
 chown puplib:puplib $MOD_DIR || error_exit "Cannot change permissions of $MOD_DIR"
+
+# Create log directory
+echo "Creating log directories"
+mkdir -m 750 -p $LOG_DIR/nginx/ || error_exit "Cannot create $LOG_DIR"
+touch $LOG_DIR/nginx/error.log || error_exit "Cannot create $LOG_DIR/nginx/error.log"
+touch $LOG_DIR/nginx/access.log || error_exit "Cannot create $LOG_DIR/nginx/access.log"
+chown -R puplib:puplib $LOG_DIR || error_exit "Cannot change permissions of $LOG_DIR"
 
 echo "Thank you for installing Puppet Library!"
 
